
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const AdjustmentsSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	documentReference: Joi.string().trim().required().messages({
        'any.required': 'documentReference is required.',
        'string.empty': 'documentReference must be a valid string.',
      }),
 	postingDate: Joi.string().trim().required().messages({
        'any.required': 'postingDate is required.',
        'string.empty': 'postingDate must be a valid string.',
      }),
 	remarks: Joi.string().trim().required().messages({
        'any.required': 'remarks is required.',
        'string.empty': 'remarks must be a valid text.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      }),
 	totalAmount: Joi.string().trim().required().messages({
        'any.required': 'totalAmount is required.',
        'string.empty': 'totalAmount must be a valid decimal.',
      }),
 	createdDate: Joi.string().trim().required().messages({
        'any.required': 'createdDate is required.',
        'string.empty': 'createdDate must be a valid string.',
      }),
 	createdBy: Joi.string().trim().required().messages({
        'any.required': 'createdBy is required.',
        'string.empty': 'createdBy must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const AdjustmentsField = {
    Id: 'id',
    DocumentReference: 'document_reference',
    PostingDate: 'posting_date',
    Remarks: 'remarks',
    Status: 'status',
    TotalAmount: 'total_amount',
    CreatedDate: 'created_date',
    CreatedBy: 'created_by',
    All: ['id', 'document_reference', 'posting_date', 'remarks', 'status', 'total_amount', 'created_date', 'created_by'],
};


module.exports = {
  AdjustmentsSchema,
  AdjustmentsField, 
};
