
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const CashDisbursementAttachmentsSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	cashDisburssementId: Joi.number().integer().required().messages({
        'any.required': 'cashDisburssementId is required.',
        'number.base': 'cashDisburssementId must be a valid integer.',
      }),
 	file: Joi.string().trim().required().messages({
        'any.required': 'file is required.',
        'string.empty': 'file must be a valid text.',
      }),
 	name: Joi.string().trim().required().messages({
        'any.required': 'name is required.',
        'string.empty': 'name must be a valid string.',
      }),
 	remarks: Joi.string().trim().required().messages({
        'any.required': 'remarks is required.',
        'string.empty': 'remarks must be a valid text.',
      }),
 	uploadedBy: Joi.string().trim().required().messages({
        'any.required': 'uploadedBy is required.',
        'string.empty': 'uploadedBy must be a valid string.',
      }),
 	uploadedDate: Joi.string().trim().required().messages({
        'any.required': 'uploadedDate is required.',
        'string.empty': 'uploadedDate must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const CashDisbursementAttachmentsField = {
    Id: 'id',
    CashDisburssementId: 'cash_disburssement_id',
    File: 'file',
    Name: 'name',
    Remarks: 'remarks',
    UploadedBy: 'uploaded_by',
    UploadedDate: 'uploaded_date',
    All: ['id', 'cash_disburssement_id', 'file', 'name', 'remarks', 'uploaded_by', 'uploaded_date'],
};


module.exports = {
  CashDisbursementAttachmentsSchema,
  CashDisbursementAttachmentsField, 
};
