// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const ChartsOfAccountsSchema = Joi.object({
	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
	code: Joi.string().trim().required().messages({
        'any.required': 'code is required.',
        'string.empty': 'code must be a valid string.',
      }),
	name: Joi.string().trim().required().messages({
        'any.required': 'name is required.',
        'string.empty': 'name must be a valid string.',
      }),
	type: Joi.string().trim().required().messages({
        'any.required': 'type is required.',
        'string.empty': 'type must be a valid enum.',
      }),
	description: Joi.string().trim().required().messages({
        'any.required': 'description is required.',
        'string.empty': 'description must be a valid string.',
      }),
	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const ChartsOfAccountsField = {
    Id: 'id',
    Code: 'code',
    Name: 'name',
    Type: 'type',
    Description: 'description',
    Status: 'status',
    All: ['id', 'code', 'name', 'type', 'description', 'status'],
};


module.exports = {
  ChartsOfAccountsSchema,
  ChartsOfAccountsField, 
};
