
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const CollectionItemsSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	collectionId: Joi.number().integer().required().messages({
        'any.required': 'collectionId is required.',
        'number.base': 'collectionId must be a valid integer.',
      }),
 	salesId: Joi.number().integer().required().messages({
        'any.required': 'salesId is required.',
        'number.base': 'salesId must be a valid integer.',
      }),
 	amount: Joi.string().trim().required().messages({
        'any.required': 'amount is required.',
        'string.empty': 'amount must be a valid decimal.',
      }),
 	witholdingTax: Joi.string().trim().required().messages({
        'any.required': 'witholdingTax is required.',
        'string.empty': 'witholdingTax must be a valid decimal.',
      })
});


/** Field references for clean, type-safe access */
const CollectionItemsField = {
    Id: 'id',
    CollectionId: 'collection_id',
    SalesId: 'sales_id',
    Amount: 'amount',
    WitholdingTax: 'witholding_tax',
    All: ['id', 'collection_id', 'sales_id', 'amount', 'witholding_tax'],
};


module.exports = {
  CollectionItemsSchema,
  CollectionItemsField, 
};
