
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const ConversationMessageSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid bigint.',
      }),
 	conId: Joi.number().integer().required().messages({
        'any.required': 'conId is required.',
        'number.base': 'conId must be a valid bigint.',
      }),
 	senderId: Joi.number().integer().required().messages({
        'any.required': 'senderId is required.',
        'number.base': 'senderId must be a valid bigint.',
      }),
 	message: Joi.string().trim().required().messages({
        'any.required': 'message is required.',
        'string.empty': 'message must be a valid text.',
      }),
 	type: Joi.string().trim().required().messages({
        'any.required': 'type is required.',
        'string.empty': 'type must be a valid enum.',
      }),
 	file: Joi.string().trim().required().messages({
        'any.required': 'file is required.',
        'string.empty': 'file must be a valid string.',
      }),
 	seen: Joi.string().trim().required().messages({
        'any.required': 'seen is required.',
        'string.empty': 'seen must be a valid tinyint.',
      }),
 	createdAt: Joi.string().trim().required().messages({
        'any.required': 'createdAt is required.',
        'string.empty': 'createdAt must be a valid datetime.',
      })
});


/** Field references for clean, type-safe access */
const ConversationMessageField = {
    Id: 'id',
    ConId: 'con_id',
    SenderId: 'sender_id',
    Message: 'message',
    Type: 'type',
    File: 'file',
    Seen: 'seen',
    CreatedAt: 'created_at',
    All: ['id', 'con_id', 'sender_id', 'message', 'type', 'file', 'seen', 'created_at'],
};


module.exports = {
  ConversationMessageSchema,
  ConversationMessageField, 
};
