
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const ConversationSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid bigint.',
      }),
 	userId: Joi.number().integer().required().messages({
        'any.required': 'userId is required.',
        'number.base': 'userId must be a valid bigint.',
      }),
 	adminId: Joi.number().integer().required().messages({
        'any.required': 'adminId is required.',
        'number.base': 'adminId must be a valid bigint.',
      }),
 	createdAt: Joi.string().trim().required().messages({
        'any.required': 'createdAt is required.',
        'string.empty': 'createdAt must be a valid datetime.',
      }),
 	lastMessageAt: Joi.string().trim().required().messages({
        'any.required': 'lastMessageAt is required.',
        'string.empty': 'lastMessageAt must be a valid datetime.',
      })
});


/** Field references for clean, type-safe access */
const ConversationField = {
    Id: 'id',
    UserId: 'user_id',
    AdminId: 'admin_id',
    CreatedAt: 'created_at',
    LastMessageAt: 'last_message_at',
    All: ['id', 'user_id', 'admin_id', 'created_at', 'last_message_at'],
};


module.exports = {
  ConversationSchema,
  ConversationField, 
};
