
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const CustomersInformationSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	customerCode: Joi.string().trim().required().messages({
        'any.required': 'customerCode is required.',
        'string.empty': 'customerCode must be a valid string.',
      }),
 	customerName: Joi.string().trim().required().messages({
        'any.required': 'customerName is required.',
        'string.empty': 'customerName must be a valid string.',
      }),
 	address: Joi.string().trim().required().messages({
        'any.required': 'address is required.',
        'string.empty': 'address must be a valid text.',
      }),
 	tin: Joi.string().trim().required().messages({
        'any.required': 'tin is required.',
        'string.empty': 'tin must be a valid string.',
      }),
 	details: Joi.string().trim().required().messages({
        'any.required': 'details is required.',
        'string.empty': 'details must be a valid text.',
      }),
 	contact: Joi.string().trim().required().messages({
        'any.required': 'contact is required.',
        'string.empty': 'contact must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const CustomersInformationField = {
    Id: 'id',
    CustomerCode: 'customer_code',
    CustomerName: 'customer_name',
    Address: 'address',
    Tin: 'tin',
    Details: 'details',
    Contact: 'contact',
    All: ['id', 'customer_code', 'customer_name', 'address', 'tin', 'details', 'contact'],
};


module.exports = {
  CustomersInformationSchema,
  CustomersInformationField, 
};
