
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const HomePageSettingsSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid bigint.',
      }),
 	welcomeBadge: Joi.string().trim().required().messages({
        'any.required': 'welcomeBadge is required.',
        'string.empty': 'welcomeBadge must be a valid string.',
      }),
 	heroTitle: Joi.string().trim().required().messages({
        'any.required': 'heroTitle is required.',
        'string.empty': 'heroTitle must be a valid text.',
      }),
 	heroDescription: Joi.string().trim().required().messages({
        'any.required': 'heroDescription is required.',
        'string.empty': 'heroDescription must be a valid text.',
      }),
 	backgroundValue: Joi.string().trim().required().messages({
        'any.required': 'backgroundValue is required.',
        'string.empty': 'backgroundValue must be a valid text.',
      }),
 	contactNumber: Joi.string().trim().required().messages({
        'any.required': 'contactNumber is required.',
        'string.empty': 'contactNumber must be a valid string.',
      }),
 	contactEmail: Joi.string().trim().required().messages({
        'any.required': 'contactEmail is required.',
        'string.empty': 'contactEmail must be a valid string.',
      }),
 	websiteTitle: Joi.string().trim().required().messages({
        'any.required': 'websiteTitle is required.',
        'string.empty': 'websiteTitle must be a valid string.',
      }),
 	websiteLogo: Joi.string().trim().required().messages({
        'any.required': 'websiteLogo is required.',
        'string.empty': 'websiteLogo must be a valid text.',
      }),
 	location: Joi.string().trim().required().messages({
        'any.required': 'location is required.',
        'string.empty': 'location must be a valid string.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      }),
 	createdAt: Joi.string().trim().required().messages({
        'any.required': 'createdAt is required.',
        'string.empty': 'createdAt must be a valid datetime.',
      }),
 	updatedAt: Joi.string().trim().required().messages({
        'any.required': 'updatedAt is required.',
        'string.empty': 'updatedAt must be a valid datetime.',
      })
});


/** Field references for clean, type-safe access */
const HomePageSettingsField = {
    Id: 'id',
    WelcomeBadge: 'welcome_badge',
    HeroTitle: 'hero_title',
    HeroDescription: 'hero_description',
    BackgroundValue: 'background_value',
    ContactNumber: 'contact_number',
    ContactEmail: 'contact_email',
    WebsiteTitle: 'website_title',
    WebsiteLogo: 'website_logo',
    Location: 'location',
    Status: 'status',
    CreatedAt: 'created_at',
    UpdatedAt: 'updated_at',
    All: ['id', 'welcome_badge', 'hero_title', 'hero_description', 'background_value', 'contact_number', 'contact_email', 'website_title', 'website_logo', 'location', 'status', 'created_at', 'updated_at'],
};


module.exports = {
  HomePageSettingsSchema,
  HomePageSettingsField, 
};
