
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const JournalEntriesSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	dbName: Joi.string().trim().required().messages({
        'any.required': 'dbName is required.',
        'string.empty': 'dbName must be a valid string.',
      }),
 	dbId: Joi.number().integer().required().messages({
        'any.required': 'dbId is required.',
        'number.base': 'dbId must be a valid integer.',
      }),
 	coaId: Joi.number().integer().required().messages({
        'any.required': 'coaId is required.',
        'number.base': 'coaId must be a valid integer.',
      }),
 	responsibilityCenter: Joi.string().trim().required().messages({
        'any.required': 'responsibilityCenter is required.',
        'string.empty': 'responsibilityCenter must be a valid string.',
      }),
 	type: Joi.string().trim().required().messages({
        'any.required': 'type is required.',
        'string.empty': 'type must be a valid enum.',
      }),
 	amount: Joi.string().trim().required().messages({
        'any.required': 'amount is required.',
        'string.empty': 'amount must be a valid decimal.',
      }),
 	date: Joi.string().trim().required().messages({
        'any.required': 'date is required.',
        'string.empty': 'date must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const JournalEntriesField = {
    Id: 'id',
    DbName: 'db_name',
    DbId: 'db_id',
    CoaId: 'coa_id',
    ResponsibilityCenter: 'responsibility_center',
    Type: 'type',
    Amount: 'amount',
    Date: 'date',
    All: ['id', 'db_name', 'db_id', 'coa_id', 'responsibility_center', 'type', 'amount', 'date'],
};


module.exports = {
  JournalEntriesSchema,
  JournalEntriesField, 
};
