
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const MasterRouteAccessSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	accessId: Joi.number().integer().required().messages({
        'any.required': 'accessId is required.',
        'number.base': 'accessId must be a valid integer.',
      }),
 	name: Joi.string().trim().required().messages({
        'any.required': 'name is required.',
        'string.empty': 'name must be a valid string.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const MasterRouteAccessField = {
    Id: 'id',
    AccessId: 'access_id',
    Name: 'name',
    Status: 'status',
    All: ['id', 'access_id', 'name', 'status'],
};


module.exports = {
  MasterRouteAccessSchema,
  MasterRouteAccessField, 
};
