
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const MasterCategorySchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid bigint.',
      }),
 	name: Joi.string().trim().required().messages({
        'any.required': 'name is required.',
        'string.empty': 'name must be a valid string.',
      }),
 	details: Joi.string().trim().required().messages({
        'any.required': 'details is required.',
        'string.empty': 'details must be a valid string.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid string.',
      }),
 	createdAt: Joi.string().trim().required().messages({
        'any.required': 'createdAt is required.',
        'string.empty': 'createdAt must be a valid string.',
      }),
 	updatedAt: Joi.string().trim().required().messages({
        'any.required': 'updatedAt is required.',
        'string.empty': 'updatedAt must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const MasterCategoryField = {
    Id: 'id',
    Name: 'name',
    Details: 'details',
    Status: 'status',
    CreatedAt: 'created_at',
    UpdatedAt: 'updated_at',
    All: ['id', 'name', 'details', 'status', 'created_at', 'updated_at'],
};


module.exports = {
  MasterCategorySchema,
  MasterCategoryField, 
};
