
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const MasterUserSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid bigint.',
      }),
 	fullname: Joi.string().trim().required().messages({
        'any.required': 'fullname is required.',
        'string.empty': 'fullname must be a valid string.',
      }),
 	email: Joi.string().trim().required().messages({
        'any.required': 'email is required.',
        'string.empty': 'email must be a valid string.',
      }),
 	password: Joi.string().trim().required().messages({
        'any.required': 'password is required.',
        'string.empty': 'password must be a valid string.',
      }),
 	role: Joi.string().trim().required().messages({
        'any.required': 'role is required.',
        'string.empty': 'role must be a valid enum.',
      }),
 	profile: Joi.string().trim().required().messages({
        'any.required': 'profile is required.',
        'string.empty': 'profile must be a valid string.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid tinyint.',
      }),
 	createdAt: Joi.string().trim().required().messages({
        'any.required': 'createdAt is required.',
        'string.empty': 'createdAt must be a valid datetime.',
      })
});


/** Field references for clean, type-safe access */
const MasterUserField = {
    Id: 'id',
    Fullname: 'fullname',
    Email: 'email',
    Password: 'password',
    Role: 'role',
    Profile: 'profile',
    Status: 'status',
    CreatedAt: 'created_at',
    All: ['id', 'fullname', 'email', 'password', 'role', 'profile', 'status', 'created_at'],
};


module.exports = {
  MasterUserSchema,
  MasterUserField, 
};
