
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const MasterAccessSchema = Joi.object({
 	accessId: Joi.number().integer().required().messages({
        'any.required': 'accessId is required.',
        'number.base': 'accessId must be a valid integer.',
      }),
 	accessName: Joi.string().trim().required().messages({
        'any.required': 'accessName is required.',
        'string.empty': 'accessName must be a valid string.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const MasterAccessField = {
    AccessId: 'access_id',
    AccessName: 'access_name',
    Status: 'status',
    All: ['access_id', 'access_name', 'status'],
};


module.exports = {
  MasterAccessSchema,
  MasterAccessField, 
};
