
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const MasterCompanySchema = Joi.object({
 	companyId: Joi.number().integer().required().messages({
        'any.required': 'companyId is required.',
        'number.base': 'companyId must be a valid integer.',
      }),
 	companyName: Joi.string().trim().required().messages({
        'any.required': 'companyName is required.',
        'string.empty': 'companyName must be a valid string.',
      }),
 	ownerName: Joi.string().trim().required().messages({
        'any.required': 'ownerName is required.',
        'string.empty': 'ownerName must be a valid string.',
      }),
 	logo: Joi.string().trim().required().messages({
        'any.required': 'logo is required.',
        'string.empty': 'logo must be a valid text.',
      }),
 	address: Joi.string().trim().required().messages({
        'any.required': 'address is required.',
        'string.empty': 'address must be a valid text.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const MasterCompanyField = {
    CompanyId: 'company_id',
    CompanyName: 'company_name',
    OwnerName: 'owner_name',
    Logo: 'logo',
    Address: 'address',
    Status: 'status',
    All: ['company_id', 'company_name', 'owner_name', 'logo', 'address', 'status'],
};


module.exports = {
  MasterCompanySchema,
  MasterCompanyField, 
};
