
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const PaymentsSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	vendorId: Joi.number().integer().required().messages({
        'any.required': 'vendorId is required.',
        'number.base': 'vendorId must be a valid integer.',
      }),
 	documentReference: Joi.string().trim().required().messages({
        'any.required': 'documentReference is required.',
        'string.empty': 'documentReference must be a valid string.',
      }),
 	modeOfPayment: Joi.string().trim().required().messages({
        'any.required': 'modeOfPayment is required.',
        'string.empty': 'modeOfPayment must be a valid enum.',
      }),
 	bankName: Joi.string().trim().required().messages({
        'any.required': 'bankName is required.',
        'string.empty': 'bankName must be a valid string.',
      }),
 	checkNumber: Joi.string().trim().required().messages({
        'any.required': 'checkNumber is required.',
        'string.empty': 'checkNumber must be a valid text.',
      }),
 	paymentDate: Joi.string().trim().required().messages({
        'any.required': 'paymentDate is required.',
        'string.empty': 'paymentDate must be a valid string.',
      }),
 	remarks: Joi.string().trim().required().messages({
        'any.required': 'remarks is required.',
        'string.empty': 'remarks must be a valid text.',
      }),
 	state: Joi.string().trim().required().messages({
        'any.required': 'state is required.',
        'string.empty': 'state must be a valid enum.',
      }),
 	createdDate: Joi.string().trim().required().messages({
        'any.required': 'createdDate is required.',
        'string.empty': 'createdDate must be a valid string.',
      }),
 	createdBy: Joi.string().trim().required().messages({
        'any.required': 'createdBy is required.',
        'string.empty': 'createdBy must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const PaymentsField = {
    Id: 'id',
    VendorId: 'vendor_id',
    DocumentReference: 'document_reference',
    ModeOfPayment: 'mode_of_payment',
    BankName: 'bank_name',
    CheckNumber: 'check_number',
    PaymentDate: 'payment_date',
    Remarks: 'remarks',
    State: 'state',
    CreatedDate: 'created_date',
    CreatedBy: 'created_by',
    All: ['id', 'vendor_id', 'document_reference', 'mode_of_payment', 'bank_name', 'check_number', 'payment_date', 'remarks', 'state', 'created_date', 'created_by'],
};


module.exports = {
  PaymentsSchema,
  PaymentsField, 
};
