
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const PaymentItemsSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	paymentId: Joi.number().integer().required().messages({
        'any.required': 'paymentId is required.',
        'number.base': 'paymentId must be a valid integer.',
      }),
 	purchaseId: Joi.number().integer().required().messages({
        'any.required': 'purchaseId is required.',
        'number.base': 'purchaseId must be a valid integer.',
      }),
 	amount: Joi.string().trim().required().messages({
        'any.required': 'amount is required.',
        'string.empty': 'amount must be a valid decimal.',
      }),
 	witholdingTax: Joi.string().trim().required().messages({
        'any.required': 'witholdingTax is required.',
        'string.empty': 'witholdingTax must be a valid decimal.',
      })
});


/** Field references for clean, type-safe access */
const PaymentItemsField = {
    Id: 'id',
    PaymentId: 'payment_id',
    PurchaseId: 'purchase_id',
    Amount: 'amount',
    WitholdingTax: 'witholding_tax',
    All: ['id', 'payment_id', 'purchase_id', 'amount', 'witholding_tax'],
};


module.exports = {
  PaymentItemsSchema,
  PaymentItemsField, 
};
