
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const PostSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid bigint.',
      }),
 	muId: Joi.number().integer().required().messages({
        'any.required': 'muId is required.',
        'number.base': 'muId must be a valid bigint.',
      }),
 	mcId: Joi.number().integer().required().messages({
        'any.required': 'mcId is required.',
        'number.base': 'mcId must be a valid bigint.',
      }),
 	content: Joi.string().trim().required().messages({
        'any.required': 'content is required.',
        'string.empty': 'content must be a valid text.',
      }),
 	embedUrl: Joi.string().trim().required().messages({
        'any.required': 'embedUrl is required.',
        'string.empty': 'embedUrl must be a valid string.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      }),
 	createdAt: Joi.string().trim().required().messages({
        'any.required': 'createdAt is required.',
        'string.empty': 'createdAt must be a valid datetime.',
      }),
 	updatedAt: Joi.string().trim().required().messages({
        'any.required': 'updatedAt is required.',
        'string.empty': 'updatedAt must be a valid datetime.',
      })
});


/** Field references for clean, type-safe access */
const PostField = {
    Id: 'id',
    MuId: 'mu_id',
    McId: 'mc_id',
    Content: 'content',
    EmbedUrl: 'embed_url',
    Status: 'status',
    CreatedAt: 'created_at',
    UpdatedAt: 'updated_at',
    All: ['id', 'mu_id', 'mc_id', 'content', 'embed_url', 'status', 'created_at', 'updated_at'],
};


module.exports = {
  PostSchema,
  PostField, 
};
