
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const PostViewSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid bigint.',
      }),
 	postId: Joi.number().integer().required().messages({
        'any.required': 'postId is required.',
        'number.base': 'postId must be a valid bigint.',
      }),
 	muId: Joi.number().integer().required().messages({
        'any.required': 'muId is required.',
        'number.base': 'muId must be a valid bigint.',
      }),
 	guestToken: Joi.string().trim().required().messages({
        'any.required': 'guestToken is required.',
        'string.empty': 'guestToken must be a valid string.',
      }),
 	viewSeconds: Joi.number().integer().required().messages({
        'any.required': 'viewSeconds is required.',
        'number.base': 'viewSeconds must be a valid integer.',
      }),
 	videoSeconds: Joi.number().integer().required().messages({
        'any.required': 'videoSeconds is required.',
        'number.base': 'videoSeconds must be a valid integer.',
      }),
 	createdAt: Joi.string().trim().required().messages({
        'any.required': 'createdAt is required.',
        'string.empty': 'createdAt must be a valid datetime.',
      })
});


/** Field references for clean, type-safe access */
const PostViewField = {
    Id: 'id',
    PostId: 'post_id',
    MuId: 'mu_id',
    GuestToken: 'guest_token',
    ViewSeconds: 'view_seconds',
    VideoSeconds: 'video_seconds',
    CreatedAt: 'created_at',
    All: ['id', 'post_id', 'mu_id', 'guest_token', 'view_seconds', 'video_seconds', 'created_at'],
};


module.exports = {
  PostViewSchema,
  PostViewField, 
};
