
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const PostLikeSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid bigint.',
      }),
 	postId: Joi.number().integer().required().messages({
        'any.required': 'postId is required.',
        'number.base': 'postId must be a valid bigint.',
      }),
 	muId: Joi.number().integer().required().messages({
        'any.required': 'muId is required.',
        'number.base': 'muId must be a valid bigint.',
      }),
 	createdAt: Joi.string().trim().required().messages({
        'any.required': 'createdAt is required.',
        'string.empty': 'createdAt must be a valid datetime.',
      })
});


/** Field references for clean, type-safe access */
const PostLikeField = {
    Id: 'id',
    PostId: 'post_id',
    MuId: 'mu_id',
    CreatedAt: 'created_at',
    All: ['id', 'post_id', 'mu_id', 'created_at'],
};


module.exports = {
  PostLikeSchema,
  PostLikeField, 
};
