
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const PostMediaSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid bigint.',
      }),
 	postId: Joi.number().integer().required().messages({
        'any.required': 'postId is required.',
        'number.base': 'postId must be a valid bigint.',
      }),
 	type: Joi.string().trim().required().messages({
        'any.required': 'type is required.',
        'string.empty': 'type must be a valid enum.',
      }),
 	path: Joi.string().trim().required().messages({
        'any.required': 'path is required.',
        'string.empty': 'path must be a valid string.',
      }),
 	sort: Joi.number().integer().required().messages({
        'any.required': 'sort is required.',
        'number.base': 'sort must be a valid integer.',
      })
});


/** Field references for clean, type-safe access */
const PostMediaField = {
    Id: 'id',
    PostId: 'post_id',
    Type: 'type',
    Path: 'path',
    Sort: 'sort',
    All: ['id', 'post_id', 'type', 'path', 'sort'],
};


module.exports = {
  PostMediaSchema,
  PostMediaField, 
};
