
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const PostMediaSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid bigint.',
      }),
 	postId: Joi.number().integer().required().messages({
        'any.required': 'postId is required.',
        'number.base': 'postId must be a valid bigint.',
      }),
 	media: Joi.string().trim().required().messages({
        'any.required': 'media is required.',
        'string.empty': 'media must be a valid longtext.',
      }),
 	sort: Joi.number().integer().required().messages({
        'any.required': 'sort is required.',
        'number.base': 'sort must be a valid integer.',
      })
});


/** Field references for clean, type-safe access */
const PostMediaField = {
    Id: 'id',
    PostId: 'post_id',
    Media: 'media',
    Sort: 'sort',
    All: ['id', 'post_id', 'media', 'sort'],
};


module.exports = {
  PostMediaSchema,
  PostMediaField, 
};
