
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const ProductsServiceSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	code: Joi.string().trim().required().messages({
        'any.required': 'code is required.',
        'string.empty': 'code must be a valid string.',
      }),
 	name: Joi.string().trim().required().messages({
        'any.required': 'name is required.',
        'string.empty': 'name must be a valid string.',
      }),
 	type: Joi.string().trim().required().messages({
        'any.required': 'type is required.',
        'string.empty': 'type must be a valid enum.',
      }),
 	category: Joi.string().trim().required().messages({
        'any.required': 'category is required.',
        'string.empty': 'category must be a valid string.',
      }),
 	salesPrice: Joi.number().integer().required().messages({
        'any.required': 'salesPrice is required.',
        'number.base': 'salesPrice must be a valid integer.',
      }),
 	purchasePrice: Joi.number().integer().required().messages({
        'any.required': 'purchasePrice is required.',
        'number.base': 'purchasePrice must be a valid integer.',
      }),
 	unit: Joi.string().trim().required().messages({
        'any.required': 'unit is required.',
        'string.empty': 'unit must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const ProductsServiceField = {
    Id: 'id',
    Code: 'code',
    Name: 'name',
    Type: 'type',
    Category: 'category',
    SalesPrice: 'sales_price',
    PurchasePrice: 'purchase_price',
    Unit: 'unit',
    All: ['id', 'code', 'name', 'type', 'category', 'sales_price', 'purchase_price', 'unit'],
};


module.exports = {
  ProductsServiceSchema,
  ProductsServiceField, 
};
