// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const ProformaEntriesSchema = Joi.object({
	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
	module: Joi.string().trim().required().messages({
        'any.required': 'module is required.',
        'string.empty': 'module must be a valid string.',
      }),
	name: Joi.string().trim().required().messages({
        'any.required': 'name is required.',
        'string.empty': 'name must be a valid string.',
      }),
	coaId: Joi.number().integer().required().messages({
        'any.required': 'coaId is required.',
        'number.base': 'coaId must be a valid integer.',
      }),
	tAccount: Joi.string().trim().required().messages({
        'any.required': 'tAccount is required.',
        'string.empty': 'tAccount must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const ProformaEntriesField = {
    Id: 'id',
    Module: 'module',
    Name: 'name',
    CoaId: 'coa_id',
    TAccount: 't_account',
    All: ['id', 'module', 'name', 'coa_id', 't_account'],
};


module.exports = {
  ProformaEntriesSchema,
  ProformaEntriesField, 
};
