
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const PurchaseSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	vendorId: Joi.number().integer().required().messages({
        'any.required': 'vendorId is required.',
        'number.base': 'vendorId must be a valid integer.',
      }),
 	documentReference: Joi.string().trim().required().messages({
        'any.required': 'documentReference is required.',
        'string.empty': 'documentReference must be a valid string.',
      }),
 	terms: Joi.string().trim().required().messages({
        'any.required': 'terms is required.',
        'string.empty': 'terms must be a valid enum.',
      }),
 	dateDelivered: Joi.string().trim().required().messages({
        'any.required': 'dateDelivered is required.',
        'string.empty': 'dateDelivered must be a valid string.',
      }),
 	dateDue: Joi.string().trim().required().messages({
        'any.required': 'dateDue is required.',
        'string.empty': 'dateDue must be a valid string.',
      }),
 	remarks: Joi.string().trim().required().messages({
        'any.required': 'remarks is required.',
        'string.empty': 'remarks must be a valid text.',
      }),
 	totalAmountDue: Joi.string().trim().required().messages({
        'any.required': 'totalAmountDue is required.',
        'string.empty': 'totalAmountDue must be a valid decimal.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      }),
 	state: Joi.string().trim().required().messages({
        'any.required': 'state is required.',
        'string.empty': 'state must be a valid enum.',
      }),
 	createdDate: Joi.string().trim().required().messages({
        'any.required': 'createdDate is required.',
        'string.empty': 'createdDate must be a valid string.',
      }),
 	createdBy: Joi.string().trim().required().messages({
        'any.required': 'createdBy is required.',
        'string.empty': 'createdBy must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const PurchaseField = {
    Id: 'id',
    VendorId: 'vendor_id',
    DocumentReference: 'document_reference',
    Terms: 'terms',
    DateDelivered: 'date_delivered',
    DateDue: 'date_due',
    Remarks: 'remarks',
    TotalAmountDue: 'total_amount_due',
    Status: 'status',
    State: 'state',
    CreatedDate: 'created_date',
    CreatedBy: 'created_by',
    All: ['id', 'vendor_id', 'document_reference', 'terms', 'date_delivered', 'date_due', 'remarks', 'total_amount_due', 'status', 'state', 'created_date', 'created_by'],
};


module.exports = {
  PurchaseSchema,
  PurchaseField, 
};
