// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const ReceiptSchema = Joi.object({
	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
	customerId: Joi.number().integer().required().messages({
        'any.required': 'customerId is required.',
        'number.base': 'customerId must be a valid integer.',
      }),
	documentReference: Joi.string().trim().required().messages({
        'any.required': 'documentReference is required.',
        'string.empty': 'documentReference must be a valid string.',
      }),
	collectionDate: Joi.string().trim().required().messages({
        'any.required': 'collectionDate is required.',
        'string.empty': 'collectionDate must be a valid string.',
      }),
	modeOfPayment: Joi.string().trim().required().messages({
        'any.required': 'modeOfPayment is required.',
        'string.empty': 'modeOfPayment must be a valid string.',
      }),
	bankName: Joi.string().trim().required().messages({
        'any.required': 'bankName is required.',
        'string.empty': 'bankName must be a valid string.',
      }),
	checkNumber: Joi.string().trim().required().messages({
        'any.required': 'checkNumber is required.',
        'string.empty': 'checkNumber must be a valid string.',
      }),
	category: Joi.string().trim().required().messages({
        'any.required': 'category is required.',
        'string.empty': 'category must be a valid string.',
      }),
	remarks: Joi.string().trim().required().messages({
        'any.required': 'remarks is required.',
        'string.empty': 'remarks must be a valid string.',
      }),
	totalAmountDue: Joi.number().precision(2).required().messages({
        'any.required': 'totalAmountDue is required.',
        'number.base': 'totalAmountDue must be a valid decimal.',
      }),
	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      }),
	state: Joi.string().trim().required().messages({
        'any.required': 'state is required.',
        'string.empty': 'state must be a valid enum.',
      }),
	createdDate: Joi.string().trim().required().messages({
        'any.required': 'createdDate is required.',
        'string.empty': 'createdDate must be a valid string.',
      }),
	createdBy: Joi.string().trim().required().messages({
        'any.required': 'createdBy is required.',
        'string.empty': 'createdBy must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const ReceiptField = {
    Id: 'id',
    CustomerId: 'customer_id',
    DocumentReference: 'document_reference',
    CollectionDate: 'collection_date',
    ModeOfPayment: 'mode_of_payment',
    BankName: 'bank_name',
    CheckNumber: 'check_number',
    Category: 'category',
    Remarks: 'remarks',
    TotalAmountDue: 'total_amount_due',
    Status: 'status',
    State: 'state',
    CreatedDate: 'created_date',
    CreatedBy: 'created_by',
    All: ['id', 'customer_id', 'document_reference', 'collection_date', 'mode_of_payment', 'bank_name', 'check_number', 'category', 'remarks', 'total_amount_due', 'status', 'state', 'created_date', 'created_by'],
};


module.exports = {
  ReceiptSchema,
  ReceiptField, 
};
