
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const VatSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	code: Joi.string().trim().required().messages({
        'any.required': 'code is required.',
        'string.empty': 'code must be a valid string.',
      }),
 	name: Joi.string().trim().required().messages({
        'any.required': 'name is required.',
        'string.empty': 'name must be a valid string.',
      }),
 	rate: Joi.string().trim().required().messages({
        'any.required': 'rate is required.',
        'string.empty': 'rate must be a valid decimal.',
      }),
 	type: Joi.string().trim().required().messages({
        'any.required': 'type is required.',
        'string.empty': 'type must be a valid enum.',
      }),
 	subType: Joi.string().trim().required().messages({
        'any.required': 'subType is required.',
        'string.empty': 'subType must be a valid enum.',
      }),
 	description: Joi.string().trim().required().messages({
        'any.required': 'description is required.',
        'string.empty': 'description must be a valid text.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const VatField = {
    Id: 'id',
    Code: 'code',
    Name: 'name',
    Rate: 'rate',
    Type: 'type',
    SubType: 'sub_type',
    Description: 'description',
    Status: 'status',
    All: ['id', 'code', 'name', 'rate', 'type', 'sub_type', 'description', 'status'],
};


module.exports = {
  VatSchema,
  VatField, 
};
