
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const VendorsInformationSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	vendorCode: Joi.string().trim().required().messages({
        'any.required': 'vendorCode is required.',
        'string.empty': 'vendorCode must be a valid string.',
      }),
 	vendorName: Joi.string().trim().required().messages({
        'any.required': 'vendorName is required.',
        'string.empty': 'vendorName must be a valid string.',
      }),
 	address: Joi.string().trim().required().messages({
        'any.required': 'address is required.',
        'string.empty': 'address must be a valid text.',
      }),
 	tin: Joi.string().trim().required().messages({
        'any.required': 'tin is required.',
        'string.empty': 'tin must be a valid string.',
      }),
 	details: Joi.string().trim().required().messages({
        'any.required': 'details is required.',
        'string.empty': 'details must be a valid text.',
      }),
 	contact: Joi.string().trim().required().messages({
        'any.required': 'contact is required.',
        'string.empty': 'contact must be a valid string.',
      })
});


/** Field references for clean, type-safe access */
const VendorsInformationField = {
    Id: 'id',
    VendorCode: 'vendor_code',
    VendorName: 'vendor_name',
    Address: 'address',
    Tin: 'tin',
    Details: 'details',
    Contact: 'contact',
    All: ['id', 'vendor_code', 'vendor_name', 'address', 'tin', 'details', 'contact'],
};


module.exports = {
  VendorsInformationSchema,
  VendorsInformationField, 
};
