
// THIS FILE IS AUTO-GENERATED by a script.
// Joi data types and error messages are automatically mapped for INSERT/UPDATE.

const Joi = require('joi');

const WithholdingTaxSchema = Joi.object({
 	id: Joi.number().integer().required().messages({
        'any.required': 'id is required.',
        'number.base': 'id must be a valid integer.',
      }),
 	code: Joi.string().trim().required().messages({
        'any.required': 'code is required.',
        'string.empty': 'code must be a valid string.',
      }),
 	name: Joi.string().trim().required().messages({
        'any.required': 'name is required.',
        'string.empty': 'name must be a valid string.',
      }),
 	rate: Joi.string().trim().required().messages({
        'any.required': 'rate is required.',
        'string.empty': 'rate must be a valid decimal.',
      }),
 	taxAccount: Joi.string().trim().required().messages({
        'any.required': 'taxAccount is required.',
        'string.empty': 'taxAccount must be a valid string.',
      }),
 	description: Joi.string().trim().required().messages({
        'any.required': 'description is required.',
        'string.empty': 'description must be a valid text.',
      }),
 	status: Joi.string().trim().required().messages({
        'any.required': 'status is required.',
        'string.empty': 'status must be a valid enum.',
      })
});


/** Field references for clean, type-safe access */
const WithholdingTaxField = {
    Id: 'id',
    Code: 'code',
    Name: 'name',
    Rate: 'rate',
    TaxAccount: 'tax_account',
    Description: 'description',
    Status: 'status',
    All: ['id', 'code', 'name', 'rate', 'tax_account', 'description', 'status'],
};


module.exports = {
  WithholdingTaxSchema,
  WithholdingTaxField, 
};
