const { healthRouter } = require('../routes/health.routes')
const { usersRouter } = require('../routes/users.routes')
const { credentialsRouter } = require('../routes/credentials.routes')
const { authRouter } = require('../routes/auth.routes')
const { adminRouter } = require('../routes/admin.routes')
const { dashboardRouter } = require('../routes/dashboard.routes')
const { postRouter } = require('../routes/post.routes')
const appointmentRouter = require('../routes/appointment.routes')
const userManagementRouter = require('../routes/userManagement.routes')
const adminDashboardRouter = require('../routes/adminDashboard.routes')
const { categoryRouter } = require('../routes/category.routes')
const postCommentRouter = require('../routes/postComment.routes')
const postLikeRouter = require('../routes/postLike.routes')

const initRoutes = (app) => {
  app.use('/credentials', credentialsRouter)
  app.use('/health', healthRouter)
  app.use('/auth', authRouter)
  app.use('/admin', adminRouter)
  app.use('/dashboard', dashboardRouter)
  app.use('/posts', postRouter)
  app.use('/users', usersRouter)
  app.use('/api/appointments', appointmentRouter)
  app.use('/api/users', userManagementRouter)
  app.use('/api/admin', adminDashboardRouter)
  app.use('/api/categories', categoryRouter)
  app.use('/api/comments', postCommentRouter)
  app.use('/api/likes', postLikeRouter)
}

module.exports = { initRoutes }
